version: '3.4'

services:

  app:
    build:
      context: .
    restart: always
    volumes:
      type: bind
      source: data
      target: /var/lib/postgresql/data
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
