version: '3.2'

services:

  app:
    build:
      context: .
    restart: on-failure
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    ports:
      - ${DB_PORT}:5432
    volumes:
      - "./data/database_cluster:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
