version: 2.1

jobs:

  linting:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Run code linting
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install flake8 | cat && test ${PIPESTATUS} -eq 0
            flake8 --count

  testing:
    machine: true
    steps:
      - checkout
      - run: docker-compose up
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports

workflows:
  version: 2
  linting:
    jobs:
      - linting
  testing:
    jobs:
      - testing
