version: 2.1

jobs:

  linting:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Run code linting
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install flake8 | cat && test ${PIPESTATUS} -eq 0
            flake8 --count

  testing:
    machine: true
    steps:
      - checkout
      - run:
          name: Pull postgres container and install app
          command: |
            mkdir test-reports
            POSTGRES_DB=postgres POSTGRES_USER=postgres POSTGRES_PASSWORD=password docker run -d -p 5433:5432 \
              --name postgres-finances-automation postgres:11
            python -m venv venv
            . venv/bin/activate
            pip install -e .[development] | cat && test ${PIPESTATUS} -eq 0
      - run:
          name: Run tests
          command: |
            pytest finances_automation/tests/ \
              --junit-xml=test-reports/junit.xml \
              --cov=finances-automation \
              --cov-report html
      - store_test_results:
          path: test-reports

workflows:
  version: 2
  linting:
    jobs:
      - linting
  testing:
    jobs:
      - testing
