version: 2.1

jobs:

  linting:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Run code linting
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install flake8 | cat && test ${PIPESTATUS} -eq 0
            flake8 --count

  testing:
    machine: true
    steps:
      - checkout
      - run:
          name: Build docker network and run tests
          command: |
            mkdir test-reports
            FINANCES_AUTOMATION_DB_PASSWORD=password docker-compose -f docker/docker-compose.yml up \
            --abort-on-container-exit --exit-code-from app
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports

workflows:
  version: 2
  linting:
    jobs:
      - linting
  testing:
    jobs:
      - testing
